Update CloudFront invalidation and introduce API Gateway

diff --git a/.github/workflows/s3-release.yml b/.github/workflows/s3-release.yml
--- a/.github/workflows/s3-release.yml
+++ b/.github/workflows/s3-release.yml
@@ -44,14 +44,13 @@ jobs:
       
       - name: Invalidate AWS CLOUDFRONT cache
         run: |
-             aws cloudfront create-invalidation \
-                --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
-                --paths \
-                "/install/install-RedHat/*" \
-                "/install/install-Debian/*" \
-                "/install/install.sh" \
-                "/install/install-Debian.sh" \
-                "/install/install-RedHat.sh" \
-                "/install/group-install.sh" \
-                "/install/workspace-install.sh" \
-                "/install/workspace-enterprise-install.sh"
+          CF_STATUS=$(aws cloudfront create-invalidation \
+            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID_OCI }} \
+            --paths "/install/*" --query 'Invalidation.Status' --output text)
+          echo "CloudFront invalidation: $CF_STATUS"
+
+          API_STATUS=$(aws apigateway test-invoke-method --rest-api-id ${{ secrets.AWS_REST_API_ID }} --resource-id "${{ secrets.AWS_RESOURCE_ID }}" \
+            --http-method PUT --path-with-query-string "/prod/static-site-oo-com" --body "$(jq -c -n '.paths = $ARGS.positional' --args "/install/*")" \
+            --region us-east-1 --query 'status' --output text || :)
+
+          echo "API Gateway test-invoke status: ${API_STATUS:-<failed>}"
